### PR TITLE
additional checks for type safety

### PR DESCRIPTION
**Pull request by cm-rudolph**
Implemented type checks as in [spring-security taglib](https://github.com/spring-projects/spring-security/blob/master/taglibs/src/main/java/org/springframework/security/taglibs/authz/AbstractAuthorizeTag.java#L188).

### CODE REVIEW

**Comment by danielfernandez** [comment]
Thanks Christian, your code looks OK and in line with what is done at the Spring Security tag library.

In order to merge your pull request I need you to read https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.1.4.RELEASE/CONTRIBUTING.markdown and please add a comment here explicitly stating you agree to the terms established there, with a link to this file. This is a requirement for all first-time pull requests from anyone.

**Comment by cm-rudolph** [comment]
I read the terms and conditions under https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.1.4.RELEASE/CONTRIBUTING.markdown carefully and agree to the terms established there.

**Comment by danielfernandez** [comment]
Thanks so much

**Comment by danielfernandez** [comment]
Hi again Christian. 

The Thymeleaf - Spring Security 4 integration module has just been released. If you want to appear at http://www.thymeleaf.org/team.html as a contributor, please send me an email with your name, forum ID (if any), location (country) and email (non-corporate) and I'll be happy to add you there.

**Pull request merged**
